name:                betfair-exchange-hi-lo-odds
version:             0.1.0.0

default-extensions:
  - NoImplicitPrelude
  - RecordWildCards

ghc-options:
  - -Wall
  - -Werror
  - -fhelpful-errors

dependencies:
  - Decimal
  - base >= 4.7 && < 5
  - bytestring
  - case-insensitive
  - connection
  - containers
  - data-default-class
  - directory
  - http-client
  - http-client-tls
  - lens
  - mtl
  - ncurses
  - table-layout
  - text
  - transformers
  - vector
  - wreq
  - xml-conduit

library:
  source-dirs: src
  c-sources:
    - c/prob.h
    - c/prob.c

executables:
  betfair-exe:
    main:                Main.hs
    source-dirs:
      - app/common
      - app/betfair-exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - betfair-exchange-hi-lo-odds
    - bytestring
    - mtl
    - temporary
    - time
    - filepath

  betfair-from-stdin:
    main:                Main.hs
    source-dirs:
      - app/common
      - app/betfair-from-stdin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - betfair-exchange-hi-lo-odds
    - temporary
    - time
    - filepath
